name: Wii U Plugin CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Install devkitPro repo + pacman
      - name: Install devkitPro
        run: |
          sudo apt-get update
          sudo apt-get install -y wget ca-certificates gnupg

          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x install-devkitpro-pacman
          sudo ./install-devkitpro-pacman

      # Install Wii U toolchain
      - name: Install Wii U devkit
        run: |
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --noconfirm wiiu-dev

      # Build plugin
      - name: Build
        run: make

      # Upload output
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wiiu-plugin
          path: |
            *.wps
            *.elf